[build]
  functions = "functions-built/"
  command = "npm run build"
  publish = "public/"
[dev]
  command="yarn dev"
  port=5000
  publish="public"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200