export const TOP_TAGS = [
  "rock",
  "electronic",
  "seen live",
  "alternative",
  "indie",
  "pop",
  "female vocalists",
  "metal",
  "alternative rock",
  "jazz",
  "classic rock",
  "ambient",
  "experimental",
  "folk",
  "punk",
  "indie rock",
  "hard rock",
  "hip hop",
  "instrumental",
  "singer songwriter",
  "black metal",
  "dance",
  "80s",
  "progressive rock",
  "death metal",
  "heavy metal",
  "hardcore",
  "british",
  "soul",
  "chillout",
  "electronica",
  "classical",
  "industrial",
  "rap",
  "soundtrack",
  "blues",
  "punk rock",
  "thrash metal",
  "90s",
  "acoustic",
  "metalcore",
  "psychedelic",
  "japanese",
  "post rock",
  "german",
  "progressive metal",
  "hip hop",
  "funk",
  "new wave",
  "trance",
  "emo",
  "pop punk",
  "grunge"
];
